"""Added group description

Revision ID: 03628111f5cd
Revises: 7dd20fd5c06b
Create Date: 2026-07-13 13:56:22.790415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03628111f5cd'
down_revision = '7dd20fd5c06b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=2048), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_group', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
