"""Added risk assessment

Revision ID: 095916721299
Revises: c4fff63bd447
Create Date: 2026-06-17 21:27:58.475161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095916721299'
down_revision = 'c4fff63bd447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk_assessment', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_token', schema=None) as batch_op:
        batch_op.drop_column('risk_assessment')

    # ### end Alembic commands ###
