"""added totp factor

Revision ID: 0eb36eeb7cd6
Revises: fadc9c6b58cf
Create Date: 2026-02-03 12:33:07.863430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0eb36eeb7cd6'
down_revision = 'fadc9c6b58cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_factor', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('totp_factor')

    # ### end Alembic commands ###
