"""renamed app setting

Revision ID: 4c3cc2af38d8
Revises: 71dcdce50d31
Create Date: 2026-07-06 13:52:29.123809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c3cc2af38d8'
down_revision = '71dcdce50d31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid36', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.String(length=2048), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_setting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_setting_uuid36'), ['uuid36'], unique=True)

    with op.batch_alter_table('app_setting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_setting_uuid36'))

    op.drop_table('app_setting')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_setting',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid36', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=2048), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('app_setting_pkey'))
    )
    with op.batch_alter_table('app_setting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_setting_uuid36'), ['uuid36'], unique=True)

    with op.batch_alter_table('system_setting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_setting_uuid36'))

    op.drop_table('system_setting')
    # ### end Alembic commands ###
