"""Changed permission value to boolean

Revision ID: 531d098e6a4e
Revises: c891dc388358
Create Date: 2026-06-23 10:05:47.622792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '531d098e6a4e'
down_revision = 'c891dc388358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_permission', schema=None) as batch_op:
        batch_op.alter_column('value',
                              existing_type=sa.VARCHAR(length=2048),
                              type_=sa.Boolean(),
                              existing_nullable=False,
                              # Add this line below:
                              postgresql_using='value::boolean')

        # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_permission', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=2048),
               existing_nullable=False)

    # ### end Alembic commands ###
