"""Updated risk score again

Revision ID: 543fb87433e3
Revises: 7fb49e984278
Create Date: 2026-06-18 18:27:48.498316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '543fb87433e3'
down_revision = '7fb49e984278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_token', schema=None) as batch_op:
        batch_op.alter_column('risk_assessment',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_token', schema=None) as batch_op:
        batch_op.alter_column('risk_assessment',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)

    # ### end Alembic commands ###
