"""Added auth source and link login token

Revision ID: 6524345cea14
Revises: f6c92a0e90ff
Create Date: 2026-05-07 16:12:22.546134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6524345cea14'
down_revision = 'f6c92a0e90ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_token_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'login_token', ['login_token_id'], ['id'])

    with op.batch_alter_table('login_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_source', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_token', schema=None) as batch_op:
        batch_op.drop_column('auth_source')

    with op.batch_alter_table('login_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('login_token_id')

    # ### end Alembic commands ###
