"""Added user groups

Revision ID: 7dd20fd5c06b
Revises: a69844252ba0
Create Date: 2026-07-13 11:14:28.234993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dd20fd5c06b'
down_revision = 'a69844252ba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid36', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_group_uuid36'), ['uuid36'], unique=True)

    op.create_table('user_group_members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['user_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_group_members')
    with op.batch_alter_table('user_group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_group_uuid36'))

    op.drop_table('user_group')
    # ### end Alembic commands ###
