"""Remove device identifiers in favor of user agents

Revision ID: 7fb49e984278
Revises: af3fed9dd642
Create Date: 2026-06-18 18:21:40.162095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fb49e984278'
down_revision = 'af3fed9dd642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_device_device_hash'))
        batch_op.drop_column('device_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_hash', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
        batch_op.create_index(batch_op.f('ix_user_device_device_hash'), ['device_hash'], unique=True)

    # ### end Alembic commands ###
