"""Reoved user link

Revision ID: 826c96b20278
Revises: d69b2489b464
Create Date: 2026-07-01 13:38:13.796647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '826c96b20278'
down_revision = 'd69b2489b464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_notification', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_notification_sender_id_fkey'), type_='foreignkey')
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('user_notification_sender_id_fkey'), 'user', ['sender_id'], ['id'])

    # ### end Alembic commands ###
