"""Changed user agent string location

Revision ID: 9e481d309a26
Revises: 095916721299
Create Date: 2026-06-18 13:20:02.197367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e481d309a26'
down_revision = '095916721299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_record', schema=None) as batch_op:
        batch_op.drop_column('user_agent')

    with op.batch_alter_table('user_device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agent', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_device', schema=None) as batch_op:
        batch_op.drop_column('user_agent')

    with op.batch_alter_table('login_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agent', sa.VARCHAR(length=512), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
