"""Added account impersonation to auth token

Revision ID: a69844252ba0
Revises: 4c3cc2af38d8
Create Date: 2026-07-13 09:24:07.411352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a69844252ba0'
down_revision = '4c3cc2af38d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('for_impersonation', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_token', schema=None) as batch_op:
        batch_op.drop_column('for_impersonation')

    # ### end Alembic commands ###
