"""removed unneeded columns from device

Revision ID: af3fed9dd642
Revises: 9e481d309a26
Create Date: 2026-06-18 18:02:43.988156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af3fed9dd642'
down_revision = '9e481d309a26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_device', schema=None) as batch_op:
        batch_op.drop_column('key')
        batch_op.drop_column('value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_device', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.VARCHAR(length=2048), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('key', sa.VARCHAR(length=128), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
