"""Added phone number verification to token

Revision ID: bfd683610539
Revises: df59b7ace6fb
Create Date: 2026-01-16 18:45:06.530598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfd683610539'
down_revision = 'df59b7ace6fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verify_phone_number', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_token', schema=None) as batch_op:
        batch_op.drop_column('verify_phone_number')

    # ### end Alembic commands ###
