"""Added device table

Revision ID: c4fff63bd447
Revises: 6524345cea14
Create Date: 2026-06-17 20:46:30.822496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4fff63bd447'
down_revision = '6524345cea14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid36', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_hash', sa.String(length=32), nullable=False),
    sa.Column('last_authenticated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_trusted', sa.Boolean(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.String(length=2048), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_device_device_hash'), ['device_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_device_uuid36'), ['uuid36'], unique=True)

    with op.batch_alter_table('login_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_device_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user_device', ['user_device_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_device_id')

    with op.batch_alter_table('user_device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_device_uuid36'))
        batch_op.drop_index(batch_op.f('ix_user_device_device_hash'))

    op.drop_table('user_device')
    # ### end Alembic commands ###
