"""changed group character count

Revision ID: d56b57d78627
Revises: 03628111f5cd
Create Date: 2026-07-13 13:59:52.901405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd56b57d78627'
down_revision = '03628111f5cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_group', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=2048),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_group', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=2048),
               existing_nullable=True)

    # ### end Alembic commands ###
