"""initial setup

Revision ID: df59b7ace6fb
Revises: 
Create Date: 2026-01-13 15:57:50.034870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df59b7ace6fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid36', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_number_verified', sa.Boolean(), nullable=False),
    sa.Column('totp_verified', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_uuid36'), ['uuid36'], unique=True)

    op.create_table('login_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid36', sa.String(length=36), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_record_uuid36'), ['uuid36'], unique=True)

    op.create_table('login_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid36', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hashed_token', sa.String(length=256), nullable=False),
    sa.Column('expiration', sa.DateTime(timezone=True), nullable=False),
    sa.Column('immediate_login', sa.Boolean(), nullable=False),
    sa.Column('next_url', sa.String(length=2048), nullable=True),
    sa.Column('remember_login', sa.Boolean(), nullable=False),
    sa.Column('reset_password', sa.Boolean(), nullable=True),
    sa.Column('risk_score', sa.Numeric(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_token_hashed_token'), ['hashed_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_login_token_risk_score'), ['risk_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_token_uuid36'), ['uuid36'], unique=True)

    op.create_table('user_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid36', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.String(length=2048), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_setting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_setting_uuid36'), ['uuid36'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_setting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_setting_uuid36'))

    op.drop_table('user_setting')
    with op.batch_alter_table('login_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_token_uuid36'))
        batch_op.drop_index(batch_op.f('ix_login_token_risk_score'))
        batch_op.drop_index(batch_op.f('ix_login_token_hashed_token'))

    op.drop_table('login_token')
    with op.batch_alter_table('login_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_record_uuid36'))

    op.drop_table('login_record')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_uuid36'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
