"""Added create account column

Revision ID: f6c92a0e90ff
Revises: 0eb36eeb7cd6
Create Date: 2026-05-07 13:53:41.121584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6c92a0e90ff'
down_revision = '0eb36eeb7cd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_account', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_token', schema=None) as batch_op:
        batch_op.drop_column('create_account')

    # ### end Alembic commands ###
