"""updated profile picure settings

Revision ID: f8e46b5a550f
Revises: 8d3f27c1a609
Create Date: 2026-10-05 19:48:56.194784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8e46b5a550f'
down_revision = '8d3f27c1a609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attached', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('attached')

    # ### end Alembic commands ###
