"""added totp entity

Revision ID: fadc9c6b58cf
Revises: a2eb57e01fe6
Create Date: 2026-02-03 10:36:00.257080

"""
import uuid

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fadc9c6b58cf'
down_revision = 'a2eb57e01fe6'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Add the column allowing NULLs first, without the unique constraint yet
    op.add_column('user', sa.Column('totp_entity', sa.String(length=36), nullable=True))

    # 2. Use Postgres's built-in uuid_generate_v4() or gen_random_uuid()
    # to give every existing row a unique value.
    # Note: 'gen_random_uuid()' works on Postgres 13+ without extra extensions.
    op.execute('UPDATE "user" SET totp_entity = gen_random_uuid()::text')

    # 3. Now that every row has a unique value, apply the constraints
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('totp_entity', nullable=False)
        batch_op.create_unique_constraint('uq_user_totp_entity', ['totp_entity'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('totp_entity')

    # ### end Alembic commands ###
